### 2. Numpy
- python에서 사용하는 과학계산용 패키지
- c, c++, 포트란으로 만들어짐
- 느린 파이썬의 연산을 보완해주는 역할
- 선형대수연산
    - 스칼라 : 하나의 수 : 5
    - 벡터 : 1차원 리스트 : `[1, 2, 3]`
    - 매트릭스 : 2차원 행렬 : `[[1, 2], [3, 4]]`
    - 텐서 : 3차원 이상
- ndarray - CRUD

In [5]:
import numpy as np

In [1]:
# 1. 행렬 데이터 생성 : ndarray : 하나의 데이터 타입만 사용 가능

In [7]:
data = np.array([1, 2, 3])
type(data), data

(numpy.ndarray, array([1, 2, 3]))

In [8]:
data = np.array([[1, 2, 4], [2, 3, 5]])
data

array([[1, 2, 4],
       [2, 3, 5]])

In [11]:
data.ndim, data.shape, data.dtype

(2, (2, 3), dtype('int64'))

In [13]:
# random data 

data1 = np.random.rand(10) # 균등분포로 랜덤데이터 생성
data2 = np.random.randn(10) # 정규분포로 랜덤데이터 생성
data3 = np.random.randint(5, 10, 10) # 균등분포 정수 랜덤 데이터 생성

# data1, data2, data3

In [15]:
# seed

np.random.seed(0)
data1 = np.random.randint(5, 10, 10)

np.random.seed(0)
data2 = np.random.randint(5, 10, 10)

np.random.seed(1)
data3 = np.random.randint(5, 10, 10)

data1, data2, data3

(array([9, 5, 8, 8, 8, 6, 8, 7, 9, 5]),
 array([9, 5, 8, 8, 8, 6, 8, 7, 9, 5]),
 array([8, 9, 5, 6, 8, 5, 5, 6, 9, 9]))

In [2]:
# 2. 행렬 데이터 수정, 추가, 삭제

In [16]:
# 행렬 데이터 선택

In [20]:
data = np.random.randint(10, size=(3, 4))
data

array([[6, 9, 2, 4],
       [5, 2, 4, 2],
       [4, 7, 7, 9]])

In [22]:
# row
data[1:]

array([[5, 2, 4, 2],
       [4, 7, 7, 9]])

In [24]:
# column, row + column
data[:, 2:], data[1:, 2:]

(array([[2, 4],
        [4, 2],
        [7, 9]]),
 array([[4, 2],
        [7, 9]]))

In [3]:
# 3. 행렬 데이터의 연산

In [26]:
ls1 = [1, 2, 3]
ls2 = [4, 5, 6]

ls1 + ls2

[1, 2, 3, 4, 5, 6]

In [31]:
# dir(ls1)
ls1.__add__(ls2)

[1, 2, 3, 4, 5, 6]

In [27]:
data1 = np.array(ls1)
data2 = np.array(ls2)

data1 + data2

array([5, 7, 9])

In [30]:
# dir(data1)
data1.__add__(data2)

array([5, 7, 9])

In [32]:
# 벡터 + 스칼라

In [36]:
# 브로드 캐스팅
data1 + 10 

array([11, 12, 13])

In [33]:
# 매트릭스 + 스칼라

In [38]:
data + 10

array([[16, 19, 12, 14],
       [15, 12, 14, 12],
       [14, 17, 17, 19]])

In [34]:
# 매트릭스 + 벡터

In [40]:
data + np.array([10, 20, 30, 40])

array([[16, 29, 32, 44],
       [15, 22, 34, 42],
       [14, 27, 37, 49]])

In [44]:
# 비교연산 : filtering

In [47]:
data[data >= 5]

array([6, 9, 5, 7, 7, 9])

In [48]:
# 데이터 수정 : 데이터 선택 = 데이터
data[data >= 5] = 10
data

array([[10, 10,  2,  4],
       [10,  2,  4,  2],
       [ 4, 10, 10, 10]])

In [49]:
# 논리연산 : all(and), any(or)

In [50]:
na1 = np.array([1, 2, 3])
na2 = np.array([1, 2, 3])
na3 = np.array([1, 0, 3])

In [51]:
na1 == na2, na1 == na3

(array([ True,  True,  True]), array([ True, False,  True]))

In [52]:
np.all(na1 == na2), np.all(na1 == na3)

(True, False)

In [53]:
np.any(na1 == na2), np.any(na1 == na3)

(True, True)

In [54]:
# 4. ndarray의 함수들
# sum, mean, median, min, max, var, std
# exp, log, linspace, logspace
# unique, split, concatenate

In [56]:
ls = [1, 2, 3, 4]
np.median(ls)

2.5

In [57]:
np.exp(ls)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [58]:
np.log(ls)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [59]:
# 데이터 결합

In [60]:
data1 = np.random.randint(10, size=(2, 3))
data2 = np.random.randint(10, size=(2, 3))
data1, data2

(array([[1, 7, 0],
        [6, 9, 9]]),
 array([[7, 6, 9],
        [1, 0, 1]]))

In [61]:
np.c_[data1, data2]

array([[1, 7, 0, 7, 6, 9],
       [6, 9, 9, 1, 0, 1]])

In [62]:
np.r_[data1, data2]

array([[1, 7, 0],
       [6, 9, 9],
       [7, 6, 9],
       [1, 0, 1]])